"""Shared billing configuration, exceptions, and models."""

from .config import (
    TOKEN_PRICE_MULTIPLIER,
    MINIMUM_CREDIT_FOR_RUN,
    DEFAULT_TOKEN_COST,
    FREE_TIER_INITIAL_CREDITS,
    CREDITS_PER_DOLLAR,
    TRIAL_ENABLED,
    TRIAL_DURATION_DAYS,
    TRIAL_TIER,
    TRIAL_CREDITS,
    Tier,
    TIERS,
    CreditPackage,
    CREDIT_PACKAGES,
    get_credit_package,
    ADMIN_LIMITS,
    get_tier_by_price_id,
    get_tier_by_name,
    get_monthly_credits,
    can_purchase_credits,
    is_model_allowed,
    get_project_limit,
    get_tier_limits,
    get_thread_limit,
    get_concurrent_runs_limit,
    is_commitment_price_id,
    get_commitment_duration_months,
    get_price_type,
    get_plan_type,
)

from .exceptions import (
    BillingError,
    InsufficientCreditsError,
    SubscriptionError,
    PaymentError,
    WebhookError,
    TierNotFoundError,
    TrialError,
    ReconciliationError,
    CircuitBreakerOpenError,
)

from .cache_utils import (
    ACCOUNT_STATE_CACHE_TTL,
    invalidate_account_state_cache,
    invalidate_credit_caches,
    cache_account_state,
    get_cached_account_state,
)

__all__ = [
    # Config constants
    'TOKEN_PRICE_MULTIPLIER',
    'MINIMUM_CREDIT_FOR_RUN',
    'DEFAULT_TOKEN_COST',
    'FREE_TIER_INITIAL_CREDITS',
    'CREDITS_PER_DOLLAR',
    'TRIAL_ENABLED',
    'TRIAL_DURATION_DAYS',
    'TRIAL_TIER',
    'TRIAL_CREDITS',
    # Tier
    'Tier',
    'TIERS',
    'CreditPackage',
    'CREDIT_PACKAGES',
    'get_credit_package',
    'ADMIN_LIMITS',
    # Functions
    'get_tier_by_price_id',
    'get_tier_by_name',
    'get_monthly_credits',
    'can_purchase_credits',
    'is_model_allowed',
    'get_project_limit',
    'get_tier_limits',
    'get_thread_limit',
    'get_concurrent_runs_limit',
    'is_commitment_price_id',
    'get_commitment_duration_months',
    'get_price_type',
    'get_plan_type',
    # Exceptions
    'BillingError',
    'InsufficientCreditsError',
    'SubscriptionError',
    'PaymentError',
    'WebhookError',
    'TierNotFoundError',
    'TrialError',
    'ReconciliationError',
    'CircuitBreakerOpenError',
    # Cache
    'ACCOUNT_STATE_CACHE_TTL',
    'invalidate_account_state_cache',
    'invalidate_account_state_cache',
    'invalidate_credit_caches',
    'cache_account_state',
    'get_cached_account_state',
]
