"""Add agent_staged_files table

Revision ID: fcb99977d5b6
Revises: 7a8c9d0e1f2b
Create Date: 2025-12-30 19:50:22.973098

"""
from alembic import op
import sqlalchemy as sa
import backend.common.model
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fcb99977d5b6'
down_revision = '7a8c9d0e1f2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if 'agent_staged_files' not in inspector.get_table_names():
        op.create_table('agent_staged_files',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
        sa.Column('user_id', sa.BigInteger(), nullable=False, comment='User who uploaded the file'),
        sa.Column('filename', sa.String(length=512), nullable=False, comment='Original filename'),
        sa.Column('storage_path', sa.String(length=1024), nullable=False, comment='Path in storage backend'),
        sa.Column('file_size', sa.BigInteger(), nullable=False, comment='File size in bytes'),
        sa.Column('file_id', sa.String(length=64), nullable=False, comment='Unique file identifier'),
        sa.Column('thread_id', sa.String(length=64), nullable=True, comment='Thread ID if attached to a conversation'),
        sa.Column('mime_type', sa.String(length=256), nullable=False, comment='File MIME type'),
        sa.Column('parsed_content', sa.Text(), nullable=True, comment='Extracted text content (truncated)'),
        sa.Column('parse_status', sa.String(length=32), nullable=False, comment='Status: pending, completed, failed'),
        sa.Column('image_url', sa.String(length=1024), nullable=True, comment='Compressed image storage path'),
        sa.Column('file_metadata', sa.JSON(), nullable=True, comment='Additional file metadata (pages, dimensions, etc.)'),
        sa.Column('expires_at', backend.common.model.TimeZone(timezone=True), nullable=True, comment='When this file expires (null = never)'),
        sa.Column('created_at', backend.common.model.TimeZone(timezone=True), nullable=False),
        sa.Column('updated_at', backend.common.model.TimeZone(timezone=True), nullable=False),
        sa.Column('created_time', backend.common.model.TimeZone(timezone=True), nullable=False, comment='创建时间'),
        sa.Column('updated_time', backend.common.model.TimeZone(timezone=True), nullable=True, comment='更新时间'),
        sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], ),
        sa.PrimaryKeyConstraint('id'),
        comment='\nStaged file for chat attachments.\n\nFiles are uploaded, parsed, and stored before being attached to messages.\nThis allows for:\n- Preview generation before sending\n- Text extraction from documents\n- Image compression and optimization\n- Temporary storage with expiration\n'
        )
        # Create indexes - only if table was just created
        op.create_index(op.f('ix_agent_staged_files_expires_at'), 'agent_staged_files', ['expires_at'], unique=False)
        op.create_index(op.f('ix_agent_staged_files_file_id'), 'agent_staged_files', ['file_id'], unique=True)
        op.create_index(op.f('ix_agent_staged_files_id'), 'agent_staged_files', ['id'], unique=True)
        op.create_index(op.f('ix_agent_staged_files_thread_id'), 'agent_staged_files', ['thread_id'], unique=False)
        op.create_index(op.f('ix_agent_staged_files_user_id'), 'agent_staged_files', ['user_id'], unique=False)
    # Removed dangerous DROP TABLE commands for system tables
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkpoints',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('parent_checkpoint_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('checkpoint', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', name=op.f('checkpoints_pkey'))
    )
    op.create_index(op.f('checkpoints_thread_id_idx'), 'checkpoints', ['thread_id'], unique=False)
    op.create_table('sys_user_social',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('sid', sa.VARCHAR(length=256), autoincrement=False, nullable=False, comment='第三方用户 ID'),
    sa.Column('source', sa.VARCHAR(length=32), autoincrement=False, nullable=False, comment='第三方用户来源'),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False, comment='用户关联ID'),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='创建时间'),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('sys_user_social_pkey')),
    comment='用户社交表（OAuth2）'
    )
    op.create_index(op.f('ix_sys_user_social_id'), 'sys_user_social', ['id'], unique=True)
    op.create_table('task_result',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.VARCHAR(length=155), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('result', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('date_done', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('traceback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=155), autoincrement=False, nullable=True),
    sa.Column('args', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('kwargs', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('worker', sa.VARCHAR(length=155), autoincrement=False, nullable=True),
    sa.Column('retries', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('queue', sa.VARCHAR(length=155), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('task_result_pkey')),
    sa.UniqueConstraint('task_id', name=op.f('task_result_task_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    comment='任务结果表'
    )
    op.create_table('sys_config',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('name', sa.VARCHAR(length=32), autoincrement=False, nullable=False, comment='名称'),
    sa.Column('type', sa.VARCHAR(length=32), autoincrement=False, nullable=True, comment='类型'),
    sa.Column('key', sa.VARCHAR(length=64), autoincrement=False, nullable=False, comment='键名'),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False, comment='键值'),
    sa.Column('is_frontend', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='是否前端'),
    sa.Column('remark', sa.TEXT(), autoincrement=False, nullable=True, comment='备注'),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='创建时间'),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('sys_config_pkey')),
    sa.UniqueConstraint('key', name=op.f('sys_config_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    comment='参数配置表'
    )
    op.create_index(op.f('ix_sys_config_id'), 'sys_config', ['id'], unique=True)
    op.create_table('task_scheduler',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=False, comment='任务名称'),
    sa.Column('task', sa.VARCHAR(length=256), autoincrement=False, nullable=False, comment='要运行的 Celery 任务'),
    sa.Column('args', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='任务可接收的位置参数'),
    sa.Column('kwargs', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='任务可接收的关键字参数'),
    sa.Column('queue', sa.VARCHAR(length=256), autoincrement=False, nullable=True, comment='CELERY_TASK_QUEUES 中定义的队列'),
    sa.Column('exchange', sa.VARCHAR(length=256), autoincrement=False, nullable=True, comment='低级别 AMQP 路由的交换机'),
    sa.Column('routing_key', sa.VARCHAR(length=256), autoincrement=False, nullable=True, comment='低级别 AMQP 路由的路由密钥'),
    sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='任务开始触发的时间'),
    sa.Column('expire_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='任务不再触发的截止时间'),
    sa.Column('expire_seconds', sa.INTEGER(), autoincrement=False, nullable=True, comment='任务不再触发的秒数时间差'),
    sa.Column('type', sa.INTEGER(), autoincrement=False, nullable=False, comment='调度类型（0间隔 1定时）'),
    sa.Column('interval_every', sa.INTEGER(), autoincrement=False, nullable=True, comment='任务再次运行前的间隔周期数'),
    sa.Column('interval_period', sa.VARCHAR(length=256), autoincrement=False, nullable=True, comment='任务运行之间的周期类型'),
    sa.Column('crontab', sa.VARCHAR(length=64), autoincrement=False, nullable=True, comment='任务运行的 Crontab 计划'),
    sa.Column('one_off', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='是否仅运行一次'),
    sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='是否启用任务'),
    sa.Column('total_run_count', sa.INTEGER(), autoincrement=False, nullable=False, comment='任务触发的总次数'),
    sa.Column('last_run_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='任务最后触发的时间'),
    sa.Column('remark', sa.TEXT(), autoincrement=False, nullable=True, comment='备注'),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='创建时间'),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('task_scheduler_pkey')),
    sa.UniqueConstraint('name', name=op.f('task_scheduler_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    comment='任务调度表'
    )
    op.create_index(op.f('ix_task_scheduler_id'), 'task_scheduler', ['id'], unique=True)
    op.create_table('task_set_result',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('taskset_id', sa.VARCHAR(length=155), autoincrement=False, nullable=True),
    sa.Column('result', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('date_done', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('task_set_result_pkey')),
    sa.UniqueConstraint('taskset_id', name=op.f('task_set_result_taskset_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    comment='任务集结果表'
    )
    op.create_table('checkpoint_blobs',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'channel', 'version', name=op.f('checkpoint_blobs_pkey'))
    )
    op.create_index(op.f('checkpoint_blobs_thread_id_idx'), 'checkpoint_blobs', ['thread_id'], unique=False)
    op.create_table('sys_dict_type',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('name', sa.VARCHAR(length=32), autoincrement=False, nullable=False, comment='字典类型名称'),
    sa.Column('code', sa.VARCHAR(length=32), autoincrement=False, nullable=False, comment='字典类型编码'),
    sa.Column('remark', sa.TEXT(), autoincrement=False, nullable=True, comment='备注'),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='创建时间'),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('sys_dict_type_pkey')),
    sa.UniqueConstraint('code', name=op.f('sys_dict_type_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    comment='字典类型表'
    )
    op.create_index(op.f('ix_sys_dict_type_id'), 'sys_dict_type', ['id'], unique=True)
    op.create_table('sys_notice',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('title', sa.VARCHAR(length=64), autoincrement=False, nullable=False, comment='标题'),
    sa.Column('type', sa.INTEGER(), autoincrement=False, nullable=False, comment='类型（0：通知、1：公告）'),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False, comment='状态（0：隐藏、1：显示）'),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False, comment='内容'),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='创建时间'),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('sys_notice_pkey')),
    comment='系统通知公告表'
    )
    op.create_index(op.f('ix_sys_notice_id'), 'sys_notice', ['id'], unique=True)
    op.create_table('checkpoint_writes',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('idx', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('task_path', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', 'task_id', 'idx', name=op.f('checkpoint_writes_pkey'))
    )
    op.create_index(op.f('checkpoint_writes_thread_id_idx'), 'checkpoint_writes', ['thread_id'], unique=False)
    op.create_table('checkpoint_migrations',
    sa.Column('v', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('v', name=op.f('checkpoint_migrations_pkey'))
    )
    op.create_table('sys_dict_data',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('type_code', sa.VARCHAR(length=32), autoincrement=False, nullable=False, comment='对应的字典类型编码'),
    sa.Column('label', sa.VARCHAR(length=32), autoincrement=False, nullable=False, comment='字典标签'),
    sa.Column('value', sa.VARCHAR(length=32), autoincrement=False, nullable=False, comment='字典值'),
    sa.Column('color', sa.VARCHAR(length=32), autoincrement=False, nullable=True, comment='标签颜色'),
    sa.Column('sort', sa.INTEGER(), autoincrement=False, nullable=False, comment='排序'),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False, comment='状态（0停用 1正常）'),
    sa.Column('remark', sa.TEXT(), autoincrement=False, nullable=True, comment='备注'),
    sa.Column('type_id', sa.BIGINT(), autoincrement=False, nullable=False, comment='字典类型关联ID'),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='创建时间'),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('sys_dict_data_pkey')),
    comment='字典数据表'
    )
    op.create_index(op.f('ix_sys_dict_data_id'), 'sys_dict_data', ['id'], unique=True)
    op.create_table('gen_column',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=False, comment='列名称'),
    sa.Column('comment', sa.VARCHAR(length=256), autoincrement=False, nullable=True, comment='列描述'),
    sa.Column('type', sa.VARCHAR(length=32), autoincrement=False, nullable=False, comment='SQLA 模型列类型'),
    sa.Column('pd_type', sa.VARCHAR(length=32), autoincrement=False, nullable=False, comment='列类型对应的 pydantic 类型'),
    sa.Column('default', sa.TEXT(), autoincrement=False, nullable=True, comment='列默认值'),
    sa.Column('sort', sa.INTEGER(), autoincrement=False, nullable=True, comment='列排序'),
    sa.Column('length', sa.INTEGER(), autoincrement=False, nullable=False, comment='列长度'),
    sa.Column('is_pk', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='是否主键'),
    sa.Column('is_nullable', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='是否可为空'),
    sa.Column('gen_business_id', sa.BIGINT(), autoincrement=False, nullable=False, comment='代码生成业务ID'),
    sa.PrimaryKeyConstraint('id', name=op.f('gen_column_pkey')),
    comment='代码生成模型列表'
    )
    op.create_index(op.f('ix_gen_column_id'), 'gen_column', ['id'], unique=True)
    op.create_table('gen_business',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('app_name', sa.VARCHAR(length=64), autoincrement=False, nullable=False, comment='应用名称（英文）'),
    sa.Column('table_name', sa.VARCHAR(length=256), autoincrement=False, nullable=False, comment='表名称（英文）'),
    sa.Column('doc_comment', sa.VARCHAR(length=256), autoincrement=False, nullable=False, comment='文档注释（用于函数/参数文档）'),
    sa.Column('table_comment', sa.VARCHAR(length=256), autoincrement=False, nullable=True, comment='表描述'),
    sa.Column('class_name', sa.VARCHAR(length=64), autoincrement=False, nullable=True, comment='基础类名（默认为英文表名称）'),
    sa.Column('schema_name', sa.VARCHAR(length=64), autoincrement=False, nullable=True, comment='Schema 名称 (默认为英文表名称)'),
    sa.Column('filename', sa.VARCHAR(length=64), autoincrement=False, nullable=True, comment='基础文件名（默认为英文表名称）'),
    sa.Column('default_datetime_column', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='是否存在默认时间列'),
    sa.Column('api_version', sa.VARCHAR(length=32), autoincrement=False, nullable=False, comment='代码生成 api 版本，默认为 v1'),
    sa.Column('gen_path', sa.VARCHAR(length=256), autoincrement=False, nullable=True, comment='代码生成路径（默认为 app 根路径）'),
    sa.Column('remark', sa.TEXT(), autoincrement=False, nullable=True, comment='备注'),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='创建时间'),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('gen_business_pkey')),
    sa.UniqueConstraint('table_name', name=op.f('gen_business_table_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    comment='代码生成业务表'
    )
    op.create_index(op.f('ix_gen_business_id'), 'gen_business', ['id'], unique=True)
    op.drop_index(op.f('ix_agent_staged_files_user_id'), table_name='agent_staged_files')
    op.drop_index(op.f('ix_agent_staged_files_thread_id'), table_name='agent_staged_files')
    op.drop_index(op.f('ix_agent_staged_files_id'), table_name='agent_staged_files')
    op.drop_index(op.f('ix_agent_staged_files_file_id'), table_name='agent_staged_files')
    op.drop_index(op.f('ix_agent_staged_files_expires_at'), table_name='agent_staged_files')
    op.drop_table('agent_staged_files')
    # ### end Alembic commands ###
