"""add_sandbox_tables

Revision ID: 20250101_002
Revises: 20250101_001
Create Date: 2025-01-01 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20250101_002'
down_revision: Union[str, None] = '001_agent'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted manually ###
    op.create_table('sandboxes',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('provider', sa.String(), nullable=True),
        sa.Column('provider_sandbox_id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column('stopped_at', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column('last_activity_at', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('provider_sandbox_id')
    )
    op.create_index('idx_sandboxes_provider_sandbox_id', 'sandboxes', ['provider_sandbox_id'], unique=False)
    op.create_index('idx_sandboxes_status', 'sandboxes', ['status'], unique=False)
    op.create_index('idx_sandboxes_user_id', 'sandboxes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - adjusted manually ###
    op.drop_index('idx_sandboxes_user_id', table_name='sandboxes')
    op.drop_index('idx_sandboxes_status', table_name='sandboxes')
    op.drop_index('idx_sandboxes_provider_sandbox_id', table_name='sandboxes')
    op.drop_table('sandboxes')
    # ### end Alembic commands ###
